/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlCrearAvatar;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;

/**
 *
 * @author ANDRES ARBOLEDA
 */
public class CrearAvatar extends javax.swing.JFrame {

    /**
     * Creates new form PruebaHacerImagen
     */
    String nickName;
    Color colorea = new Color(240, 240, 240);
    Color[][] colores = new Color [8][8];
    ControlCrearAvatar cca;
    public CrearAvatar() {
        initComponents();
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Cuadricula = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLAzul = new javax.swing.JLabel();
        jLBlanco = new javax.swing.JLabel();
        jLAmarillo = new javax.swing.JLabel();
        jLAguaMarina = new javax.swing.JLabel();
        jLPiel = new javax.swing.JLabel();
        jLVerde = new javax.swing.JLabel();
        jLRojo = new javax.swing.JLabel();
        jLNegro = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jBMas = new javax.swing.JButton();
        jLAvatar5 = new javax.swing.JLabel();
        jLAvatar1 = new javax.swing.JLabel();
        jLAvatar3 = new javax.swing.JLabel();
        jLAvatar4 = new javax.swing.JLabel();
        jLAvatar2 = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cuadricula.setOpaque(false);
        Cuadricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 40, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 40, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 40, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 40, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 40, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 40, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 40, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel11MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 40, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel12MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 40, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel13MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, 40));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel14MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 40, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel15MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 40, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel16MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 40, 40));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setOpaque(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel17MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 40, 40));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.setOpaque(true);
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel18MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 40, 40));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel21MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 40, 40));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.setOpaque(true);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel22MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 40, 40));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.setOpaque(true);
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel23MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 40, 40));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel24.setOpaque(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel24MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 40, 40));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.setOpaque(true);
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel25MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 40, 40));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.setOpaque(true);
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel26MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 40, 40));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.setOpaque(true);
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel27MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 40, 40));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.setOpaque(true);
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel28MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 40, 40));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.setOpaque(true);
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel31MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 40, 40));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.setOpaque(true);
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel32MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 40, 40));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel33.setOpaque(true);
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel33MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 40, 40));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel34.setOpaque(true);
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel34MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 40, 40));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel35.setOpaque(true);
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel35MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 40, 40));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel36.setOpaque(true);
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel36MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 40, 40));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.setOpaque(true);
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel37MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 40, 40));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel38.setOpaque(true);
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel38MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 40, 40));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel41.setOpaque(true);
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel41MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 40, 40));

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel42.setOpaque(true);
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel42MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 40, 40));

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel43.setOpaque(true);
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel43MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 40, 40));

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel44.setOpaque(true);
        jLabel44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel44MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 40, 40));

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel45.setOpaque(true);
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel45MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 40, 40));

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel46.setOpaque(true);
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel46MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 40, 40));

        jLabel47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel47.setOpaque(true);
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel47MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 40, 40));

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel48.setOpaque(true);
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel48MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 40, 40));

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel51.setOpaque(true);
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel51MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 40, 40));

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel52.setOpaque(true);
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel52MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 40, 40));

        jLabel53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel53.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel53.setOpaque(true);
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel53MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 40, 40));

        jLabel54.setBackground(new java.awt.Color(255, 255, 255));
        jLabel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel54.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel54.setOpaque(true);
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel54MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 40, 40));

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel55.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel55.setOpaque(true);
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel55MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 40, 40));

        jLabel56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel56.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel56.setOpaque(true);
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel56MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 40, 40));

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel57.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel57.setOpaque(true);
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel57MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 40, 40));

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel58.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel58.setOpaque(true);
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel58MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 40, 40));

        jLabel61.setBackground(new java.awt.Color(255, 255, 255));
        jLabel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel61.setOpaque(true);
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel61MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 40, 40));

        jLabel62.setBackground(new java.awt.Color(255, 255, 255));
        jLabel62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel62.setOpaque(true);
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel62MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 40, 40));

        jLabel63.setBackground(new java.awt.Color(255, 255, 255));
        jLabel63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel63.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel63.setOpaque(true);
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel63MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 40, 40));

        jLabel64.setBackground(new java.awt.Color(255, 255, 255));
        jLabel64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel64.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel64.setOpaque(true);
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel64MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 40, 40));

        jLabel65.setBackground(new java.awt.Color(255, 255, 255));
        jLabel65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel65.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel65.setOpaque(true);
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel65MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 40, 40));

        jLabel66.setBackground(new java.awt.Color(255, 255, 255));
        jLabel66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel66.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel66.setOpaque(true);
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel66MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 40, 40));

        jLabel67.setBackground(new java.awt.Color(255, 255, 255));
        jLabel67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel67.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel67.setOpaque(true);
        jLabel67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel67MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 40, 40));

        jLabel68.setBackground(new java.awt.Color(255, 255, 255));
        jLabel68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel68.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel68.setOpaque(true);
        jLabel68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel68MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 40, 40));

        jLabel71.setBackground(new java.awt.Color(255, 255, 255));
        jLabel71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel71.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel71.setOpaque(true);
        jLabel71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel71MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 40, 40));

        jLabel72.setBackground(new java.awt.Color(255, 255, 255));
        jLabel72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel72.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel72.setOpaque(true);
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel72MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 40, 40));

        jLabel73.setBackground(new java.awt.Color(255, 255, 255));
        jLabel73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel73.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel73.setOpaque(true);
        jLabel73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel73MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 40, 40));

        jLabel74.setBackground(new java.awt.Color(255, 255, 255));
        jLabel74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel74.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel74.setOpaque(true);
        jLabel74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel74MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 40, 40));

        jLabel75.setBackground(new java.awt.Color(255, 255, 255));
        jLabel75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel75.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel75.setOpaque(true);
        jLabel75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel75MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 40, 40));

        jLabel76.setBackground(new java.awt.Color(255, 255, 255));
        jLabel76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel76.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel76.setOpaque(true);
        jLabel76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel76MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 40, 40));

        jLabel77.setBackground(new java.awt.Color(255, 255, 255));
        jLabel77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel77.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel77.setOpaque(true);
        jLabel77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel77MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 40, 40));

        jLabel78.setBackground(new java.awt.Color(255, 255, 255));
        jLabel78.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLabel78.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel78.setOpaque(true);
        jLabel78.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel78MouseReleased(evt);
            }
        });
        Cuadricula.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 40, 40));

        jLabel101.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel101.setText("1");
        Cuadricula.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 40, 40));

        jLabel102.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setText("2");
        Cuadricula.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 40, 40));

        jLabel103.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel103.setText("3");
        Cuadricula.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 40, 40));

        jLabel104.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel104.setText("4");
        Cuadricula.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 40, 40));

        jLabel105.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("5");
        Cuadricula.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, 40));

        jLabel106.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel106.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel106.setText("6");
        Cuadricula.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 40, 40));

        jLabel107.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel107.setText("7");
        Cuadricula.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 40, 40));

        jLabel108.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel108.setText("8");
        Cuadricula.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 40, 40));

        jLabel111.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel111.setText("1");
        Cuadricula.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, 40));

        jLabel112.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel112.setText("2");
        Cuadricula.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, 40));

        jLabel113.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel113.setText("3");
        Cuadricula.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 40, 40));

        jLabel114.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel114.setText("4");
        Cuadricula.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 40, 40));

        jLabel115.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel115.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel115.setText("5");
        Cuadricula.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 40, 40));

        jLabel116.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel116.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel116.setText("6");
        Cuadricula.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 40, 40));

        jLabel117.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel117.setText("7");
        Cuadricula.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 40, 40));

        jLabel118.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel118.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel118.setText("8");
        Cuadricula.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 40, 40));

        jPanel1.add(Cuadricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 490, 450));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 400, 390));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 510, 460));

        jLAzul.setBackground(new java.awt.Color(51, 102, 255));
        jLAzul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLAzul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAzul.setOpaque(true);
        jLAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLAzulMouseReleased(evt);
            }
        });
        jPanel1.add(jLAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 40, 40));

        jLBlanco.setBackground(new java.awt.Color(255, 255, 255));
        jLBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLBlanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLBlanco.setOpaque(true);
        jLBlanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLBlancoMouseReleased(evt);
            }
        });
        jPanel1.add(jLBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 40, 40));

        jLAmarillo.setBackground(new java.awt.Color(255, 255, 0));
        jLAmarillo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLAmarillo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAmarillo.setOpaque(true);
        jLAmarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLAmarilloMouseReleased(evt);
            }
        });
        jPanel1.add(jLAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 40, 40));

        jLAguaMarina.setBackground(new java.awt.Color(0, 153, 153));
        jLAguaMarina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLAguaMarina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAguaMarina.setOpaque(true);
        jLAguaMarina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLAguaMarinaMouseReleased(evt);
            }
        });
        jPanel1.add(jLAguaMarina, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 40, 40));

        jLPiel.setBackground(new java.awt.Color(244, 230, 192));
        jLPiel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLPiel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLPiel.setOpaque(true);
        jLPiel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLPielMouseReleased(evt);
            }
        });
        jPanel1.add(jLPiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 40, 40));

        jLVerde.setBackground(new java.awt.Color(0, 153, 0));
        jLVerde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLVerde.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLVerde.setOpaque(true);
        jLVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLVerdeMouseReleased(evt);
            }
        });
        jPanel1.add(jLVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 40, 40));

        jLRojo.setBackground(new java.awt.Color(255, 51, 51));
        jLRojo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLRojo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLRojo.setOpaque(true);
        jLRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLRojoMouseReleased(evt);
            }
        });
        jPanel1.add(jLRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 40, 40));

        jLNegro.setBackground(new java.awt.Color(0, 0, 0));
        jLNegro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLNegro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLNegro.setOpaque(true);
        jLNegro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLNegroMouseReleased(evt);
            }
        });
        jPanel1.add(jLNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 40, 40));

        jBGuardar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pluma.png"))); // NOI18N
        jBGuardar.setText("Crear");
        jBGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 680, 190, 80));

        jBMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton.png"))); // NOI18N
        jBMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscuchaPanel(evt);
            }
        });
        jPanel1.add(jBMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 40, 40));

        jLAvatar5.setBackground(new java.awt.Color(255, 255, 255));
        jLAvatar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatars/Avatar1/1.jpg"))); // NOI18N
        jLAvatar5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLAvatar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAvatar5.setOpaque(true);
        jLAvatar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLAvatar5MouseReleased(evt);
            }
        });
        jPanel1.add(jLAvatar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 40, 40));

        jLAvatar1.setBackground(new java.awt.Color(255, 255, 255));
        jLAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatars/Avatar2/1.jpg"))); // NOI18N
        jLAvatar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLAvatar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAvatar1.setOpaque(true);
        jLAvatar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLAvatar1MouseReleased(evt);
            }
        });
        jPanel1.add(jLAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 40, 40));

        jLAvatar3.setBackground(new java.awt.Color(255, 255, 255));
        jLAvatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatars/Avatar4/1.jpg"))); // NOI18N
        jLAvatar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLAvatar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAvatar3.setOpaque(true);
        jLAvatar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLAvatar3MouseReleased(evt);
            }
        });
        jPanel1.add(jLAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 40, 40));

        jLAvatar4.setBackground(new java.awt.Color(255, 255, 255));
        jLAvatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatars/Avatar5/1.jpg"))); // NOI18N
        jLAvatar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLAvatar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAvatar4.setOpaque(true);
        jLAvatar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLAvatar4MouseReleased(evt);
            }
        });
        jPanel1.add(jLAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 40, 40));

        jLAvatar2.setBackground(new java.awt.Color(255, 255, 255));
        jLAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatars/Avatar3/1.jpg"))); // NOI18N
        jLAvatar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jLAvatar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLAvatar2.setOpaque(true);
        jLAvatar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLAvatar2MouseReleased(evt);
            }
        });
        jPanel1.add(jLAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 40, 40));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBlanco.jpg"))); // NOI18N
        jPanel1.add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 780));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 620, 650);

        setSize(new java.awt.Dimension(638, 697));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLAzulMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAzulMouseReleased
        jPanel2.setVisible(false);
        Cuadricula.setVisible(true);
        colorea = jLAzul.getBackground();
    }//GEN-LAST:event_jLAzulMouseReleased

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        jLabel1.setBackground(colorea);
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        jLabel2.setBackground(colorea);
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        jLabel3.setBackground(colorea);
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLBlancoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBlancoMouseReleased
        jPanel2.setVisible(false);
        Cuadricula.setVisible(true);
        colorea = jLBlanco.getBackground();
    }//GEN-LAST:event_jLBlancoMouseReleased

    private void jLRojoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLRojoMouseReleased
        jPanel2.setVisible(false);
        Cuadricula.setVisible(true);
        colorea = jLRojo.getBackground();
    }//GEN-LAST:event_jLRojoMouseReleased

    private void jLAmarilloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAmarilloMouseReleased
        jPanel2.setVisible(false);
        Cuadricula.setVisible(true);
        colorea = jLAmarillo.getBackground();
    }//GEN-LAST:event_jLAmarilloMouseReleased

    private void jLVerdeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLVerdeMouseReleased
        jPanel2.setVisible(false);
        Cuadricula.setVisible(true);
        colorea = jLVerde.getBackground();
    }//GEN-LAST:event_jLVerdeMouseReleased

    private void jLPielMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPielMouseReleased
        jPanel2.setVisible(false);
        Cuadricula.setVisible(true);
        colorea = jLPiel.getBackground();
    }//GEN-LAST:event_jLPielMouseReleased

    private void jLAguaMarinaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAguaMarinaMouseReleased
        jPanel2.setVisible(false);
        Cuadricula.setVisible(true);
        colorea = jLAguaMarina.getBackground();
    }//GEN-LAST:event_jLAguaMarinaMouseReleased

    private void jLNegroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLNegroMouseReleased
        jPanel2.setVisible(false);
        Cuadricula.setVisible(true);
        colorea = jLNegro.getBackground();
    }//GEN-LAST:event_jLNegroMouseReleased

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        jLabel4.setBackground(colorea);
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        jLabel5.setBackground(colorea);
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        jLabel6.setBackground(colorea);
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
        jLabel7.setBackground(colorea);
    }//GEN-LAST:event_jLabel7MouseReleased

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        jLabel8.setBackground(colorea);
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jLabel11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseReleased
        jLabel11.setBackground(colorea);
    }//GEN-LAST:event_jLabel11MouseReleased

    private void jLabel13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseReleased
        jLabel13.setBackground(colorea);
    }//GEN-LAST:event_jLabel13MouseReleased

    private void jLabel14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseReleased
        jLabel14.setBackground(colorea);
    }//GEN-LAST:event_jLabel14MouseReleased

    private void jLabel12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseReleased
        jLabel12.setBackground(colorea);
    }//GEN-LAST:event_jLabel12MouseReleased

    private void jLabel15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseReleased
        jLabel15.setBackground(colorea);
    }//GEN-LAST:event_jLabel15MouseReleased

    private void jLabel16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseReleased
        jLabel16.setBackground(colorea);
    }//GEN-LAST:event_jLabel16MouseReleased

    private void jLabel17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseReleased
        jLabel17.setBackground(colorea);
    }//GEN-LAST:event_jLabel17MouseReleased

    private void jLabel18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseReleased
        jLabel18.setBackground(colorea);
    }//GEN-LAST:event_jLabel18MouseReleased

    private void jLabel21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseReleased
        jLabel21.setBackground(colorea);
    }//GEN-LAST:event_jLabel21MouseReleased

    private void jLabel22MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseReleased
        jLabel22.setBackground(colorea);
    }//GEN-LAST:event_jLabel22MouseReleased

    private void jLabel23MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseReleased
        jLabel23.setBackground(colorea);
    }//GEN-LAST:event_jLabel23MouseReleased

    private void jLabel24MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseReleased
        jLabel24.setBackground(colorea);
    }//GEN-LAST:event_jLabel24MouseReleased

    private void jLabel25MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseReleased
        jLabel25.setBackground(colorea);
    }//GEN-LAST:event_jLabel25MouseReleased

    private void jLabel26MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseReleased
        jLabel26.setBackground(colorea);
    }//GEN-LAST:event_jLabel26MouseReleased

    private void jLabel27MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseReleased
        jLabel27.setBackground(colorea);
    }//GEN-LAST:event_jLabel27MouseReleased

    private void jLabel28MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseReleased
        jLabel28.setBackground(colorea);
    }//GEN-LAST:event_jLabel28MouseReleased

    private void jLabel31MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseReleased
        jLabel31.setBackground(colorea);
    }//GEN-LAST:event_jLabel31MouseReleased

    private void jLabel32MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseReleased
        jLabel32.setBackground(colorea);
    }//GEN-LAST:event_jLabel32MouseReleased

    private void jLabel33MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseReleased
        jLabel33.setBackground(colorea);
    }//GEN-LAST:event_jLabel33MouseReleased

    private void jLabel34MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseReleased
        jLabel34.setBackground(colorea);
    }//GEN-LAST:event_jLabel34MouseReleased

    private void jLabel35MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseReleased
        jLabel35.setBackground(colorea);
    }//GEN-LAST:event_jLabel35MouseReleased

    private void jLabel36MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseReleased
        jLabel36.setBackground(colorea);
    }//GEN-LAST:event_jLabel36MouseReleased

    private void jLabel37MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseReleased
        jLabel37.setBackground(colorea);
    }//GEN-LAST:event_jLabel37MouseReleased

    private void jLabel38MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseReleased
        jLabel38.setBackground(colorea);
    }//GEN-LAST:event_jLabel38MouseReleased

    private void jLabel41MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseReleased
        jLabel41.setBackground(colorea);
    }//GEN-LAST:event_jLabel41MouseReleased

    private void jLabel42MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseReleased
        jLabel42.setBackground(colorea);
    }//GEN-LAST:event_jLabel42MouseReleased

    private void jLabel43MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseReleased
        jLabel43.setBackground(colorea);
    }//GEN-LAST:event_jLabel43MouseReleased

    private void jLabel44MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel44MouseReleased
        jLabel44.setBackground(colorea);
    }//GEN-LAST:event_jLabel44MouseReleased

    private void jLabel45MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseReleased
        jLabel45.setBackground(colorea);
    }//GEN-LAST:event_jLabel45MouseReleased

    private void jLabel46MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseReleased
        jLabel46.setBackground(colorea);
    }//GEN-LAST:event_jLabel46MouseReleased

    private void jLabel47MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseReleased
        jLabel47.setBackground(colorea);
    }//GEN-LAST:event_jLabel47MouseReleased

    private void jLabel48MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseReleased
        jLabel48.setBackground(colorea);
    }//GEN-LAST:event_jLabel48MouseReleased

    private void jLabel51MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseReleased
        jLabel51.setBackground(colorea);
    }//GEN-LAST:event_jLabel51MouseReleased

    private void jLabel52MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MouseReleased
        jLabel52.setBackground(colorea);
    }//GEN-LAST:event_jLabel52MouseReleased

    private void jLabel53MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MouseReleased
        jLabel53.setBackground(colorea);
    }//GEN-LAST:event_jLabel53MouseReleased

    private void jLabel54MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseReleased
        jLabel54.setBackground(colorea);
    }//GEN-LAST:event_jLabel54MouseReleased

    private void jLabel55MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseReleased
        jLabel55.setBackground(colorea);
    }//GEN-LAST:event_jLabel55MouseReleased

    private void jLabel56MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseReleased
        jLabel56.setBackground(colorea);
    }//GEN-LAST:event_jLabel56MouseReleased

    private void jLabel57MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseReleased
        jLabel57.setBackground(colorea);
    }//GEN-LAST:event_jLabel57MouseReleased

    private void jLabel58MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseReleased
        jLabel58.setBackground(colorea);
    }//GEN-LAST:event_jLabel58MouseReleased

    private void jLabel61MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseReleased
        jLabel61.setBackground(colorea);
    }//GEN-LAST:event_jLabel61MouseReleased

    private void jLabel62MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseReleased
        jLabel62.setBackground(colorea);
    }//GEN-LAST:event_jLabel62MouseReleased

    private void jLabel63MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseReleased
        jLabel63.setBackground(colorea);
    }//GEN-LAST:event_jLabel63MouseReleased

    private void jLabel64MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseReleased
        jLabel64.setBackground(colorea);
    }//GEN-LAST:event_jLabel64MouseReleased

    private void jLabel65MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseReleased
        jLabel65.setBackground(colorea);
    }//GEN-LAST:event_jLabel65MouseReleased

    private void jLabel66MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseReleased
        jLabel66.setBackground(colorea);
    }//GEN-LAST:event_jLabel66MouseReleased

    private void jLabel67MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel67MouseReleased
        jLabel67.setBackground(colorea);
    }//GEN-LAST:event_jLabel67MouseReleased

    private void jLabel68MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel68MouseReleased
        jLabel68.setBackground(colorea);
    }//GEN-LAST:event_jLabel68MouseReleased

    private void jLabel71MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel71MouseReleased
        jLabel71.setBackground(colorea);
    }//GEN-LAST:event_jLabel71MouseReleased

    private void jLabel72MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MouseReleased
        jLabel72.setBackground(colorea);
    }//GEN-LAST:event_jLabel72MouseReleased

    private void jLabel73MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel73MouseReleased
        jLabel73.setBackground(colorea);
    }//GEN-LAST:event_jLabel73MouseReleased

    private void jLabel74MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel74MouseReleased
        jLabel74.setBackground(colorea);
    }//GEN-LAST:event_jLabel74MouseReleased

    private void jLabel75MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel75MouseReleased
        jLabel75.setBackground(colorea);
    }//GEN-LAST:event_jLabel75MouseReleased

    private void jLabel76MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel76MouseReleased
        jLabel76.setBackground(colorea);
    }//GEN-LAST:event_jLabel76MouseReleased

    private void jLabel77MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel77MouseReleased
        jLabel77.setBackground(colorea);
    }//GEN-LAST:event_jLabel77MouseReleased

    private void jLabel78MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel78MouseReleased
        jLabel78.setBackground(colorea);
    }//GEN-LAST:event_jLabel78MouseReleased

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        llenarMatriz();
        preLlenarMatriz();
        GuardarNombre nick = new GuardarNombre(null, true);
        nickName = nick.getNickName();
        cca = new ControlCrearAvatar(colores, nickName);
        dispose();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void EscuchaPanel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscuchaPanel
        jPanel2.setVisible(false);
        Cuadricula.setVisible(true);
        JColorChooser panel = new JColorChooser();
        colorea=panel.showDialog(null, "PALETA DE COLORES", Color.RED);
    }//GEN-LAST:event_EscuchaPanel

    private void jLAvatar5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAvatar5MouseReleased
        Cuadricula.setVisible(false);
        jPanel2.setVisible(true);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatars/ImagenesOriginales/5.jpg")));
    }//GEN-LAST:event_jLAvatar5MouseReleased

    private void jLAvatar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAvatar1MouseReleased
        Cuadricula.setVisible(false);
        jPanel2.setVisible(true);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatars/ImagenesOriginales/1.jpg")));
    }//GEN-LAST:event_jLAvatar1MouseReleased

    private void jLAvatar3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAvatar3MouseReleased
        Cuadricula.setVisible(false);
        jPanel2.setVisible(true);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatars/ImagenesOriginales/3.jpg")));
    }//GEN-LAST:event_jLAvatar3MouseReleased

    private void jLAvatar4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAvatar4MouseReleased
        Cuadricula.setVisible(false);
        jPanel2.setVisible(true);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatars/ImagenesOriginales/4.jpg")));
    }//GEN-LAST:event_jLAvatar4MouseReleased

    private void jLAvatar2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAvatar2MouseReleased
        Cuadricula.setVisible(false);
        jPanel2.setVisible(true);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Avatars/ImagenesOriginales/2.jpg")));
    }//GEN-LAST:event_jLAvatar2MouseReleased

    public void preLlenarMatriz(){
        for (int j = 0; j < colores.length; j++) {
            for (int n = 0; n < colores[0].length; n++) {
                if(colores[j][n].equals(new Color(255,255,255))){
                    colores[j][n] = new Color(233, 233, 233);
                }
            }
        }
    }
   public void llenarMatriz(){
        int fila = 0;
        colores[fila][0] = jLabel1.getBackground();
        colores[fila][1] = jLabel2.getBackground();
        colores[fila][2] = jLabel3.getBackground();
        colores[fila][3] = jLabel4.getBackground();
        colores[fila][4] = jLabel5.getBackground();
        colores[fila][5] = jLabel6.getBackground();
        colores[fila][6] = jLabel7.getBackground();
        colores[fila][7] = jLabel8.getBackground();
        
        fila = 1;
        colores[fila][0] = jLabel11.getBackground();
        colores[fila][1] = jLabel12.getBackground();
        colores[fila][2] = jLabel13.getBackground();
        colores[fila][3] = jLabel14.getBackground();
        colores[fila][4] = jLabel15.getBackground();
        colores[fila][5] = jLabel16.getBackground();
        colores[fila][6] = jLabel17.getBackground();
        colores[fila][7] = jLabel18.getBackground();

        fila = 2;
        colores[fila][0] = jLabel21.getBackground();
        colores[fila][1] = jLabel22.getBackground();
        colores[fila][2] = jLabel23.getBackground();
        colores[fila][3] = jLabel24.getBackground();
        colores[fila][4] = jLabel25.getBackground();
        colores[fila][5] = jLabel26.getBackground();
        colores[fila][6] = jLabel27.getBackground();
        colores[fila][7] = jLabel28.getBackground();

        fila = 3;
        colores[fila][0] = jLabel31.getBackground();
        colores[fila][1] = jLabel32.getBackground();
        colores[fila][2] = jLabel33.getBackground();
        colores[fila][3] = jLabel34.getBackground();
        colores[fila][4] = jLabel35.getBackground();
        colores[fila][5] = jLabel36.getBackground();
        colores[fila][6] = jLabel37.getBackground();
        colores[fila][7] = jLabel38.getBackground();

        fila = 4;
        colores[fila][0] = jLabel41.getBackground();
        colores[fila][1] = jLabel42.getBackground();
        colores[fila][2] = jLabel43.getBackground();
        colores[fila][3] = jLabel44.getBackground();
        colores[fila][4] = jLabel45.getBackground();
        colores[fila][5] = jLabel46.getBackground();
        colores[fila][6] = jLabel47.getBackground();
        colores[fila][7] = jLabel48.getBackground();

        fila = 5;
        colores[fila][0] = jLabel51.getBackground();
        colores[fila][1] = jLabel52.getBackground();
        colores[fila][2] = jLabel53.getBackground();
        colores[fila][3] = jLabel54.getBackground();
        colores[fila][4] = jLabel55.getBackground();
        colores[fila][5] = jLabel56.getBackground();
        colores[fila][6] = jLabel57.getBackground();
        colores[fila][7] = jLabel58.getBackground();

        fila = 6;
        colores[fila][0] = jLabel61.getBackground();
        colores[fila][1] = jLabel62.getBackground();
        colores[fila][2] = jLabel63.getBackground();
        colores[fila][3] = jLabel64.getBackground();
        colores[fila][4] = jLabel65.getBackground();
        colores[fila][5] = jLabel66.getBackground();
        colores[fila][6] = jLabel67.getBackground();
        colores[fila][7] = jLabel68.getBackground();

        fila = 7;
        colores[fila][0] = jLabel71.getBackground();
        colores[fila][1] = jLabel72.getBackground();
        colores[fila][2] = jLabel73.getBackground();
        colores[fila][3] = jLabel74.getBackground();
        colores[fila][4] = jLabel75.getBackground();
        colores[fila][5] = jLabel76.getBackground();
        colores[fila][6] = jLabel77.getBackground();
        colores[fila][7] = jLabel78.getBackground();

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearAvatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearAvatar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cuadricula;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBMas;
    private javax.swing.JLabel jLAguaMarina;
    private javax.swing.JLabel jLAmarillo;
    private javax.swing.JLabel jLAvatar1;
    private javax.swing.JLabel jLAvatar2;
    private javax.swing.JLabel jLAvatar3;
    private javax.swing.JLabel jLAvatar4;
    private javax.swing.JLabel jLAvatar5;
    private javax.swing.JLabel jLAzul;
    private javax.swing.JLabel jLBlanco;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLNegro;
    private javax.swing.JLabel jLPiel;
    private javax.swing.JLabel jLRojo;
    private javax.swing.JLabel jLVerde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
