/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Sonido;

/**
 *
 * @author ANDRES ARBOLEDA
 */
public class GuardarNombre extends javax.swing.JDialog {

    /**
     * Creates new form GuardarNombre
     */
    String nickName;
    Sonido s;
    public GuardarNombre(java.awt.Frame parent, boolean modal, String mensaje) {
        super(parent, modal);
        initComponents();
        jMensaje1.setVisible(false);
        jMensaje2.setVisible(false);

        setMensaje(mensaje);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMensaje1 = new javax.swing.JLabel();
        jMensaje2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMensaje1.setFont(new java.awt.Font("Unispace", 1, 20)); // NOI18N
        jMensaje1.setForeground(new java.awt.Color(255, 102, 102));
        jMensaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMensaje1.setText("MSG 1");
        jPanel1.add(jMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 382, -1));

        jMensaje2.setFont(new java.awt.Font("Unispace", 1, 20)); // NOI18N
        jMensaje2.setForeground(new java.awt.Color(255, 102, 102));
        jMensaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMensaje2.setText("MSG 2");
        jPanel1.add(jMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 382, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese NickName");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 324, 53));

        jTextField1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 194, 58));

        jBGuardar.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBGuardar.setContentAreaFilled(false);
        jBGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 180, 50));

        jBCerrar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jBCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jBCerrar.setText("Cerrar");
        jBCerrar.setContentAreaFilled(false);
        jBCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 130, 46));

        Fondo.setFont(new java.awt.Font("Tempus Sans ITC", 3, 26)); // NOI18N
        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBlanco.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 404, -1));

        setSize(new java.awt.Dimension(418, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        s = new Sonido("click.wav");
        if(!jTextField1.getText().equals("")){
            nickName = jTextField1.getText();
            setVisible(false);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        s = new Sonido("click.wav");
        dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

    public String getNickName() {
        return nickName;
    }


    public void setMensaje(String msj){
        String[] arr = msj.split("-");
        jMensaje1.setText(arr[0]);
        jMensaje1.setVisible(true);
        
        jMensaje2.setText(arr[1]);
        jMensaje2.setVisible(true);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jMensaje1;
    private javax.swing.JLabel jMensaje2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
