/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Sonido;

/**
 *
 * @author Alejandra Becerra
 */
public class GuiaControles extends javax.swing.JDialog {

    /**
     * Creates new form GuiaControles
     */
    String menu;
    Sonido s;
    public GuiaControles(java.awt.Frame parent, boolean modal,String menu) {
        super(parent, modal);
        this.menu=menu;
        initComponents();
        llamarContenido();
        
        CrearAvat.setVisible(false);
        ControlJueg.setVisible(false);
        setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void llamarContenido(){
        CrearAvatar.setVisible(false);
        InfGeneral.setVisible(false);
        Contenido.setVisible(true);
    }
    private void llamarPaneles(boolean crearAvat,boolean controlJuego){
        Contenido.setVisible(false);
        CrearAvatar.setVisible(crearAvat);
        InfGeneral.setVisible(controlJuego);
        PersonalizarAvatar.setVisible(crearAvat);
        ControlJuego.setVisible(controlJuego);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenido = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        ControlJueg = new javax.swing.JLabel();
        ControlJueg1 = new javax.swing.JLabel();
        CrearAvat = new javax.swing.JLabel();
        CrearAvat1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        CrearAvatar = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        PersonalizarAvatar = new javax.swing.JPanel();
        Titulo5 = new javax.swing.JLabel();
        jlPersonalizarAvatar2 = new javax.swing.JPanel();
        jbMas3 = new javax.swing.JButton();
        jbImagPredeterminadas4 = new javax.swing.JButton();
        JL31 = new javax.swing.JLabel();
        jbCrear4 = new javax.swing.JButton();
        jbCargarImgPredeterm2 = new javax.swing.JButton();
        jbCargar4 = new javax.swing.JButton();
        jbCerrar4 = new javax.swing.JButton();
        jbMatrizAvatar5 = new javax.swing.JButton();
        JL32 = new javax.swing.JLabel();
        JL33 = new javax.swing.JLabel();
        JL34 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        JL35 = new javax.swing.JLabel();
        JL36 = new javax.swing.JLabel();
        JL37 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        JL38 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        CargarAvatars2 = new javax.swing.JPanel();
        JL39 = new javax.swing.JLabel();
        jbNickName2 = new javax.swing.JButton();
        jbVista4 = new javax.swing.JButton();
        jbVista5 = new javax.swing.JButton();
        JL40 = new javax.swing.JLabel();
        JL41 = new javax.swing.JLabel();
        jbMatrizAvatar6 = new javax.swing.JButton();
        JL42 = new javax.swing.JLabel();
        jbImagPredeterminadas5 = new javax.swing.JButton();
        JL43 = new javax.swing.JLabel();
        jbCrear5 = new javax.swing.JButton();
        jbCargar5 = new javax.swing.JButton();
        jbCerrar5 = new javax.swing.JButton();
        JL44 = new javax.swing.JLabel();
        JL45 = new javax.swing.JLabel();
        jbVolver4 = new javax.swing.JButton();
        InfGeneral = new javax.swing.JScrollPane();
        JPanel2 = new javax.swing.JPanel();
        ControlJuego = new javax.swing.JPanel();
        Titulo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jbVolver2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contenido.setBackground(new java.awt.Color(255, 255, 255));
        Contenido.setOpaque(false);
        Contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Times New Roman", 1, 100)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 153, 153));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("GUIA DEL JUEGO");
        Contenido.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 910, 190));

        ControlJueg.setBackground(new java.awt.Color(255, 255, 255));
        ControlJueg.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        ControlJueg.setForeground(new java.awt.Color(0, 153, 153));
        ControlJueg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ControlJueg.setText("¿CONTROLES DEL JUEGO?");
        ControlJueg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ControlJuegMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EscuchaPanelControlJuego(evt);
            }
        });
        Contenido.add(ControlJueg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 890, 90));

        ControlJueg1.setBackground(new java.awt.Color(255, 255, 255));
        ControlJueg1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        ControlJueg1.setForeground(new java.awt.Color(0, 153, 153));
        ControlJueg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ControlJueg1.setText("¿CONTROLES DEL JUEGO?");
        ControlJueg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ControlJueg1MouseEntered(evt);
            }
        });
        Contenido.add(ControlJueg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 951, 90));

        CrearAvat.setBackground(new java.awt.Color(255, 255, 255));
        CrearAvat.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        CrearAvat.setForeground(new java.awt.Color(0, 153, 153));
        CrearAvat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearAvat.setText("¿COMO CREAR UN AVATAR?");
        CrearAvat.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                CrearAvatAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        CrearAvat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearAvatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EscuchaPanelAvatar(evt);
            }
        });
        Contenido.add(CrearAvat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 890, 90));

        CrearAvat1.setBackground(new java.awt.Color(255, 255, 255));
        CrearAvat1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        CrearAvat1.setForeground(new java.awt.Color(0, 153, 153));
        CrearAvat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearAvat1.setText("¿COMO CREAR UN AVATAR?");
        CrearAvat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrearAvat1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CrearAvat1EscuchaPanelAvatar(evt);
            }
        });
        Contenido.add(CrearAvat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 900, 108));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 60)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Contenido.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 410, 70));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Fondo.setForeground(new java.awt.Color(0, 153, 153));
        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoCarton.jpg"))); // NOI18N
        Fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FondoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FondoEscuchaPanelAvatar(evt);
            }
        });
        Contenido.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 670));

        getContentPane().add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        CrearAvatar.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        PersonalizarAvatar.setBackground(new java.awt.Color(255, 255, 255));
        PersonalizarAvatar.setOpaque(false);
        PersonalizarAvatar.setRequestFocusEnabled(false);
        PersonalizarAvatar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 100)); // NOI18N
        Titulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo5.setText("CREAR AVATAR");
        PersonalizarAvatar.add(Titulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 910, 110));

        jlPersonalizarAvatar2.setBackground(new java.awt.Color(255, 255, 255));
        jlPersonalizarAvatar2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Personalizar Avatar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 36))); // NOI18N
        jlPersonalizarAvatar2.setOpaque(false);
        jlPersonalizarAvatar2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbMas3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbMas3.setToolTipText("<html>Con este boton se abrira una paleta de´<p>"
            + "colores para tener más colores si lo desea.<html>");
        jbMas3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbMas3.setContentAreaFilled(false);
        jbMas3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMas3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbMas3MouseMoved(evt);
            }
        });
        jlPersonalizarAvatar2.add(jbMas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 30, 30));

        jbImagPredeterminadas4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbImagPredeterminadas4.setToolTipText("<html>Se puede escoger una imagen predeterminada<p>"
            + "tan solo seleccionado una de las imagenes<html>");
        jbImagPredeterminadas4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbImagPredeterminadas4.setContentAreaFilled(false);
        jbImagPredeterminadas4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbImagPredeterminadas4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbImagPredeterminadas4MouseMoved(evt);
            }
        });
        jlPersonalizarAvatar2.add(jbImagPredeterminadas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 330, 50));

        JL31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CrearAvatar.png"))); // NOI18N
        JL31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlPersonalizarAvatar2.add(JL31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 110));

        jbCrear4.setToolTipText("<html>Luego de escoger o personalizar tu avatar<p>"
            + "Presiona este boton para crear tu avatar. <p>"
            + "el juego <html>");
        jbCrear4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCrear4.setContentAreaFilled(false);
        jbCrear4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlPersonalizarAvatar2.add(jbCrear4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 650, 130, 50));

        jbCargarImgPredeterm2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbCargarImgPredeterm2.setToolTipText("<html>Se puede escoger una imagen predeterminada<p>"
            + "tan solo seleccionado una de las imagenes<html>");
        jbCargarImgPredeterm2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbCargarImgPredeterm2.setContentAreaFilled(false);
        jbCargarImgPredeterm2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCargarImgPredeterm2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbCargarImgPredeterm2MouseMoved(evt);
            }
        });
        jlPersonalizarAvatar2.add(jbCargarImgPredeterm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 350, 340));

        jbCargar4.setToolTipText("<html>Al presionar este boton, se abrira otra ventana<p>"
            + "La cual podra escoger avatars de los cuales ya existen<html>");
        jbCargar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCargar4.setContentAreaFilled(false);
        jbCargar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlPersonalizarAvatar2.add(jbCargar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 650, 150, 50));

        jbCerrar4.setToolTipText("<html>Saldra una ventana de advertencia. Y Se devolvera a <p>"
            + "la ventana de menú principal<html>");
        jbCerrar4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCerrar4.setContentAreaFilled(false);
        jbCerrar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlPersonalizarAvatar2.add(jbCerrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 110, 50));

        jbMatrizAvatar5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbMatrizAvatar5.setToolTipText("<html>Si desea personalizar tu avatar, tan solo <p>"
            + "debes seleccionar colores de la parte superior <p>"
            + "y dejar volvar tu imaginación.<html>");
        jbMatrizAvatar5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbMatrizAvatar5.setContentAreaFilled(false);
        jbMatrizAvatar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlPersonalizarAvatar2.add(jbMatrizAvatar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 350, 340));

        JL32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CrearAvatar1.png"))); // NOI18N
        jlPersonalizarAvatar2.add(JL32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 350, 340));

        JL33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CargarAvatars3.png"))); // NOI18N
        jlPersonalizarAvatar2.add(JL33, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 340, 390));

        JL34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CrearAvatar2.png"))); // NOI18N
        JL34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlPersonalizarAvatar2.add(JL34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 430, 90));

        jButton24.setToolTipText("<html>Luego de presionar el boton de cargar<p>"
            + "Se abrira esta ventana para darle el <p>"
            + "nombre a su avatar, recien escogido o creado <html>");
        jButton24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton24.setContentAreaFilled(false);
        jlPersonalizarAvatar2.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 800, 380, 340));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CrearAvatar3.png"))); // NOI18N
        jlPersonalizarAvatar2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 810, 340, 300));

        JL35.setBackground(new java.awt.Color(204, 204, 204));
        JL35.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JL35.setForeground(new java.awt.Color(0, 102, 102));
        JL35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL35.setText("PASO 4");
        jlPersonalizarAvatar2.add(JL35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1160, 670, 30));

        JL36.setBackground(new java.awt.Color(204, 204, 204));
        JL36.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JL36.setForeground(new java.awt.Color(0, 102, 102));
        JL36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL36.setText("PASO 1");
        jlPersonalizarAvatar2.add(JL36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 670, 30));

        JL37.setBackground(new java.awt.Color(204, 204, 204));
        JL37.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JL37.setForeground(new java.awt.Color(0, 102, 102));
        JL37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL37.setText("PASO 2");
        jlPersonalizarAvatar2.add(JL37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 670, 30));

        jButton25.setToolTipText("<html>Luego de presionar el boton de cerrar<p>"
            + "Se abrira esta ventana de advertencia<html>");
        jButton25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton25.setContentAreaFilled(false);
        jlPersonalizarAvatar2.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 800, 360, 340));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CrearAvatar4.png"))); // NOI18N
        jlPersonalizarAvatar2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 810, 320, 300));

        JL38.setBackground(new java.awt.Color(204, 204, 204));
        JL38.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JL38.setForeground(new java.awt.Color(0, 102, 102));
        JL38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL38.setText("PASO 3");
        jlPersonalizarAvatar2.add(JL38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 750, 670, 30));

        jButton26.setToolTipText("<html>Si al crear un avatar, el nombre ingresado<p>"
            + "ya existe te dira si desea reescribirlo o no <html>");
        jButton26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton26.setContentAreaFilled(false);
        jlPersonalizarAvatar2.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1240, 380, 120));

        jButton27.setToolTipText("<html>Si presiona SI, se reescribira la imagen y<p>"
            + " comenzara el juego<html>");
        jButton27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton27.setContentAreaFilled(false);
        jlPersonalizarAvatar2.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1400, 160, 70));

        jButton28.setToolTipText("<html>Si presiona NO, deberar escribir<p>"
            + "nuevamente un nickName"
            + "<html>");
        jButton28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton28.setContentAreaFilled(false);
        jlPersonalizarAvatar2.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 1400, 170, 70));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CrearAvatar5.png"))); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlPersonalizarAvatar2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1220, 420, 270));

        PersonalizarAvatar.add(jlPersonalizarAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 860, 1570));

        CargarAvatars2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cargar Avatars", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 36))); // NOI18N
        CargarAvatars2.setOpaque(false);
        CargarAvatars2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL39.setBackground(new java.awt.Color(204, 204, 204));
        JL39.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JL39.setForeground(new java.awt.Color(0, 102, 102));
        JL39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL39.setText("PASO 1");
        CargarAvatars2.add(JL39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 600, 30));

        jbNickName2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbNickName2.setToolTipText("<html>Aqui estaran cargados todo los nickName<p>"
            + "existentes en le juego <html>");
        jbNickName2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbNickName2.setContentAreaFilled(false);
        jbNickName2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbNickName2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbNickName2MouseMoved(evt);
            }
        });
        CargarAvatars2.add(jbNickName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 260, 40));

        jbVista4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbVista4.setToolTipText("<html>Al presionar este boton nos mostrar<p>"
            + "una vista previa de la avatar que contiene<p>"
            + "el nicName<html>");
        jbVista4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbVista4.setContentAreaFilled(false);
        jbVista4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVista4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbVista4MouseMoved(evt);
            }
        });
        CargarAvatars2.add(jbVista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 50, 40));

        jbVista5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbVista5.setToolTipText("<html>Al presionar este boton nos volvera<p>"
            + "a mostrar el contenido de la creacion del <p>"
            + "avatar<html>");
        jbVista5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbVista5.setContentAreaFilled(false);
        jbVista5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVista5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbVista5MouseMoved(evt);
            }
        });
        jbVista5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVista5ActionPerformed(evt);
            }
        });
        CargarAvatars2.add(jbVista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 30, 30));

        JL40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CargarAvatars1.png"))); // NOI18N
        JL40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CargarAvatars2.add(JL40, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 410, 100));

        JL41.setBackground(new java.awt.Color(204, 204, 204));
        JL41.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JL41.setForeground(new java.awt.Color(0, 102, 102));
        JL41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL41.setText("PASO 3");
        CargarAvatars2.add(JL41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 600, 30));

        jbMatrizAvatar6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbMatrizAvatar6.setToolTipText("<html>La vista previa puede mostrar<p>"
            + "asi, de forma personalizada<html>");
        jbMatrizAvatar6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbMatrizAvatar6.setContentAreaFilled(false);
        jbMatrizAvatar6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMatrizAvatar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMatrizAvatar6ActionPerformed(evt);
            }
        });
        CargarAvatars2.add(jbMatrizAvatar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 330, 330));

        JL42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CargarAvatars2.png"))); // NOI18N
        CargarAvatars2.add(JL42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 310, 310));

        jbImagPredeterminadas5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbImagPredeterminadas5.setToolTipText("<html>La vista previa puede mostrar<p>"
            + "asi, con una imagen predecterminada<html>");
        jbImagPredeterminadas5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbImagPredeterminadas5.setContentAreaFilled(false);
        jbImagPredeterminadas5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CargarAvatars2.add(jbImagPredeterminadas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 320, 330));

        JL43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CargarAvatars3.png"))); // NOI18N
        CargarAvatars2.add(JL43, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 300, 290));

        jbCrear5.setToolTipText("<html>Luego de escoger el avatar con el cual desea<p>"
            + "jugar, presiona el boton para iniciar el juego<html>");
        jbCrear5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCrear5.setContentAreaFilled(false);
        CargarAvatars2.add(jbCrear5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 740, 130, 60));

        jbCargar5.setToolTipText("<html>Al presionar este boton, se abrira otra ventana<p>"
            + "La cual podra escoger avatars los cuales ya existen<html>");
        jbCargar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCargar5.setContentAreaFilled(false);
        CargarAvatars2.add(jbCargar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 740, 120, 60));

        jbCerrar5.setToolTipText("<html>Se devuelve a la ventana Menú<html>");
        jbCerrar5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCerrar5.setContentAreaFilled(false);
        CargarAvatars2.add(jbCerrar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 740, 110, 60));

        JL44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/CargarAvatars4.png"))); // NOI18N
        JL44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CargarAvatars2.add(JL44, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 720, 450, 100));

        JL45.setBackground(new java.awt.Color(204, 204, 204));
        JL45.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JL45.setForeground(new java.awt.Color(0, 102, 102));
        JL45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JL45.setText("PASO 2");
        CargarAvatars2.add(JL45, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 600, 30));

        PersonalizarAvatar.add(CargarAvatars2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1790, 860, 850));

        jbVolver4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jbVolver4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        jbVolver4.setText("Volver");
        jbVolver4.setContentAreaFilled(false);
        jbVolver4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVolver4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolver4volverCrearAvatar(evt);
            }
        });
        PersonalizarAvatar.add(jbVolver4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2650, 830, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 987, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PersonalizarAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2723, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PersonalizarAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        CrearAvatar.setViewportView(jPanel4);

        getContentPane().add(CrearAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 650));

        JPanel2.setBackground(new java.awt.Color(255, 255, 255));
        JPanel2.setPreferredSize(new java.awt.Dimension(1195, 2200));
        JPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ControlJuego.setBackground(new java.awt.Color(255, 255, 255));
        ControlJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 80)); // NOI18N
        Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo2.setText("CONTROL DEL JUEGO");
        ControlJuego.add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 900, 110));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Movimiento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 36))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/FlechaArriba.png"))); // NOI18N
        jButton3.setToolTipText("<html>Para que el avatar vaya hacia arriba.<html>");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 60, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/direccion.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, 190));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/FlechaDerecha.png"))); // NOI18N
        jButton5.setToolTipText("<html>Para que el avatar vaya hacia derecha.<html>");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 60, 50));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/FlechaIzquierda.png"))); // NOI18N
        jButton6.setToolTipText("<html>Para que el avatar vaya hacia izquierda.<html>");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 60, 50));

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/FlechaAbajo.png"))); // NOI18N
        jButton7.setToolTipText("<html>Para que el avatar vaya hacia abajo.<html>");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 60, 50));

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton8.setText("S");
        jButton8.setToolTipText("<html>Para que el avatar vaya hacia abajo.<html>");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 60, 50));

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton9.setText("A");
        jButton9.setToolTipText("<html>Para que el avatar vaya hacia izquierda.<html>");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 60, 50));

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton10.setText("W");
        jButton10.setToolTipText("<html>Para que el avatar vaya hacia arriba.<html>");
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 60, 50));

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jButton11.setText("D");
        jButton11.setToolTipText("<html>Para que el avatar vaya hacia derecha.<html>");
        jButton11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 60, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/direccion.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 190));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 360, 360));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 360, 360));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Movimiento del avatar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 730, 60));

        ControlJuego.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 860, 540));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Enemigos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 36))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton20.setToolTipText("<html>Cada vez que un avatar se encuentre con un enemigo<p>"
            + "entonces hara una colision, el cual devolvera al avatar al<p>"
            + "punto inicial<html>");
        jButton20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton20.setContentAreaFilled(false);
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 90, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Colision entre el enemigo y el avatar");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 44, 730, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/Colision.png"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 115, 666, 481));

        jButton21.setToolTipText("<html>Vuelve al inicio<html>");
        jButton21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton21.setContentAreaFilled(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 40, 40));

        jButton22.setToolTipText("<html>Si presiona el boton, se abrira<p>"
            + "la venta de la guia del juego<html>");
        jButton22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton22.setContentAreaFilled(false);
        jPanel2.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 670, 70, 60));

        jButton23.setToolTipText("<html>Cada jugador comenzara el juego con 3 vidas, si<p>"
            + "ocurre una colision con un enemigo ira perdiendo vidas<html>");
        jButton23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton23.setContentAreaFilled(false);
        jPanel2.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 700, 190, 40));

        jButton29.setToolTipText("<html>Por cada mundo que culmine, se sumara 100 <p>"
            + " puntos y 50 por cada vida<html>");
        jButton29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton29.setContentAreaFilled(false);
        jPanel2.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, 160, 40));

        jButton30.setToolTipText("<html>Detalla el nivel de cada mundo<html>");
        jButton30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton30.setContentAreaFilled(false);
        jPanel2.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 140, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuiaControl/informacion.png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 760, 123));

        ControlJuego.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 830, 840));

        JPanel2.add(ControlJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 1570));

        jbVolver2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jbVolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        jbVolver2.setText("Volver");
        jbVolver2.setContentAreaFilled(false);
        jbVolver2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolver2volverCrearAvatar(evt);
            }
        });
        JPanel2.add(jbVolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1580, 830, -1));

        InfGeneral.setViewportView(JPanel2);

        getContentPane().add(InfGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 650));

        setSize(new java.awt.Dimension(974, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EscuchaPanelAvatar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscuchaPanelAvatar
        s = new Sonido("click.wav");
        llamarPaneles(true, false);
    }//GEN-LAST:event_EscuchaPanelAvatar

    private void EscuchaPanelControlJuego(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EscuchaPanelControlJuego
        s = new Sonido("click.wav");
        llamarPaneles(false, true);
    }//GEN-LAST:event_EscuchaPanelControlJuego

    private void CrearAvat1EscuchaPanelAvatar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearAvat1EscuchaPanelAvatar
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearAvat1EscuchaPanelAvatar

    private void CrearAvatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearAvatMouseExited
        CrearAvat.setVisible(false);
        CrearAvat1.setVisible(true);
    }//GEN-LAST:event_CrearAvatMouseExited

    private void CrearAvat1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearAvat1MouseEntered
        CrearAvat1.setVisible(false);
        CrearAvat.setVisible(true);
    }//GEN-LAST:event_CrearAvat1MouseEntered

    private void ControlJuegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ControlJuegMouseExited
        ControlJueg.setVisible(false);
        ControlJueg1.setVisible(true);
        CrearAvatar.setVisible(false);
    }//GEN-LAST:event_ControlJuegMouseExited

    private void ControlJueg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ControlJueg1MouseEntered
        ControlJueg1.setVisible(false);
        ControlJueg.setVisible(true);
    }//GEN-LAST:event_ControlJueg1MouseEntered

    private void FondoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_FondoMouseEntered

    private void FondoEscuchaPanelAvatar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoEscuchaPanelAvatar
        // TODO add your handling code here:
    }//GEN-LAST:event_FondoEscuchaPanelAvatar

    private void CrearAvatAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_CrearAvatAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearAvatAncestorAdded

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jbVolver2volverCrearAvatar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolver2volverCrearAvatar
        llamarContenido();
        s = new Sonido("click.wav");
    }//GEN-LAST:event_jbVolver2volverCrearAvatar

    private void jbMas3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMas3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMas3MouseMoved

    private void jbImagPredeterminadas4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbImagPredeterminadas4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbImagPredeterminadas4MouseMoved

    private void jbCargarImgPredeterm2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCargarImgPredeterm2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCargarImgPredeterm2MouseMoved

    private void jbNickName2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNickName2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNickName2MouseMoved

    private void jbVista4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVista4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVista4MouseMoved

    private void jbVista5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVista5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVista5MouseMoved

    private void jbVista5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVista5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVista5ActionPerformed

    private void jbMatrizAvatar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMatrizAvatar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMatrizAvatar6ActionPerformed

    private void jbVolver4volverCrearAvatar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolver4volverCrearAvatar
        s = new Sonido("click.wav");
        llamarContenido();
    }//GEN-LAST:event_jbVolver4volverCrearAvatar

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    s = new Sonido("click.wav");
        if(!menu.equals("")){
            new Menu();
            dispose();
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      new GuiaControles(null, true,"");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CargarAvatars2;
    private javax.swing.JPanel Contenido;
    private javax.swing.JLabel ControlJueg;
    private javax.swing.JLabel ControlJueg1;
    private javax.swing.JPanel ControlJuego;
    private javax.swing.JLabel CrearAvat;
    private javax.swing.JLabel CrearAvat1;
    private javax.swing.JScrollPane CrearAvatar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JScrollPane InfGeneral;
    private javax.swing.JLabel JL31;
    private javax.swing.JLabel JL32;
    private javax.swing.JLabel JL33;
    private javax.swing.JLabel JL34;
    private javax.swing.JLabel JL35;
    private javax.swing.JLabel JL36;
    private javax.swing.JLabel JL37;
    private javax.swing.JLabel JL38;
    private javax.swing.JLabel JL39;
    private javax.swing.JLabel JL40;
    private javax.swing.JLabel JL41;
    private javax.swing.JLabel JL42;
    private javax.swing.JLabel JL43;
    private javax.swing.JLabel JL44;
    private javax.swing.JLabel JL45;
    private javax.swing.JPanel JPanel2;
    private javax.swing.JPanel PersonalizarAvatar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbCargar4;
    private javax.swing.JButton jbCargar5;
    private javax.swing.JButton jbCargarImgPredeterm2;
    private javax.swing.JButton jbCerrar4;
    private javax.swing.JButton jbCerrar5;
    private javax.swing.JButton jbCrear4;
    private javax.swing.JButton jbCrear5;
    private javax.swing.JButton jbImagPredeterminadas4;
    private javax.swing.JButton jbImagPredeterminadas5;
    private javax.swing.JButton jbMas3;
    private javax.swing.JButton jbMatrizAvatar5;
    private javax.swing.JButton jbMatrizAvatar6;
    private javax.swing.JButton jbNickName2;
    private javax.swing.JButton jbVista4;
    private javax.swing.JButton jbVista5;
    private javax.swing.JButton jbVolver2;
    private javax.swing.JButton jbVolver4;
    private javax.swing.JPanel jlPersonalizarAvatar2;
    // End of variables declaration//GEN-END:variables
}
